alias: Gestion de la Présence dans les Pièces
description: '**Statut :** Finalisé

  **Evolution :** Aucune


  **Déclencheurs :**

  - Changement d''état des capteurs de présence Aqara FP2 (Suite parentale, Bureau,
  Chambre) avec délai 5 min


  **Fonctionnement :**

  1. Selon le capteur déclenché, met à jour le sélecteur de présence correspondant.

  2. Présence détectée → sélectionne la première option (Présent).

  3. Absence détectée → sélectionne la dernière option (Absent).


  **Entités principales :**

  - `binary_sensor.presence_sensor_fp2_*` : capteurs de présence Aqara

  - `input_select.presence_bureau` / `presence_chambre` / `presence_suite_parentale`
  : états de présence par pièce'
triggers:
- trigger: state
  entity_id:
  - binary_sensor.presence_sensor_fp2_1932_presence_sensor_1
  for:
    hours: 0
    minutes: 5
    seconds: 0
  id: Présence Suite parentale
- trigger: state
  entity_id:
  - binary_sensor.presence_sensor_fp2_b226_presence_sensor_1
  for:
    hours: 0
    minutes: 5
    seconds: 0
  id: Présence Bureau
- trigger: state
  entity_id:
  - binary_sensor.presence_sensor_fp2_b21a_presence_sensor_1
  for:
    hours: 0
    minutes: 5
    seconds: 0
  id: Présence Chambre
conditions: []
actions:
- choose:
  - conditions:
    - condition: trigger
      id:
      - Présence Suite parentale
    sequence:
    - if:
      - condition: state
        entity_id: binary_sensor.presence_sensor_fp2_1932_presence_sensor_1
        state: 'on'
      then:
      - action: input_select.select_first
        metadata: {}
        data: {}
        target:
          entity_id: input_select.presence_suite_parentale
      else:
      - action: input_select.select_last
        metadata: {}
        data: {}
        target:
          entity_id: input_select.presence_suite_parentale
  - conditions:
    - condition: trigger
      id:
      - Présence Bureau
    sequence:
    - if:
      - condition: state
        entity_id: binary_sensor.presence_sensor_fp2_b226_presence_sensor_1
        state: 'on'
      then:
      - action: input_select.select_first
        metadata: {}
        data: {}
        target:
          entity_id:
          - input_select.presence_bureau
      else:
      - action: input_select.select_last
        metadata: {}
        data: {}
        target:
          entity_id:
          - input_select.presence_bureau
  - conditions:
    - condition: trigger
      id:
      - Présence Chambre
    sequence:
    - if:
      - condition: state
        entity_id: binary_sensor.presence_sensor_fp2_b21a_presence_sensor_1
        state: 'on'
      then:
      - action: input_select.select_first
        metadata: {}
        data: {}
        target:
          entity_id:
          - input_select.presence_chambre
      else:
      - action: input_select.select_last
        metadata: {}
        data: {}
        target:
          entity_id:
          - input_select.presence_chambre
mode: parallel
max: 10
