alias: Gestion de la Lumière de l'Entrée
description: >-
  **Statut :** Finalisé | **Evolution :** Aucune


  **Déclencheurs :**

  - Sonnette du portier (`binary_sensor.exterieur_slm_portier_visiteur` → on)

  - Présence devant le portier (`binary_sensor.exterieur_slm_portier_personne` →
  on)


  **Fonctionnement :**

  1. Si période sombre (30 min après coucher / 30 min avant lever du soleil) →
  allume `light.lumiere_de_lexterieur`, attend 5 s.

  2. Si la lumière est allumée → attend 5 min puis éteint automatiquement.


  > Mode `restart` : une nouvelle détection pendant le délai de 5 min relance
  l'extinction à zéro.


  **Entités utilisées :** `binary_sensor.exterieur_slm_portier_visiteur`,
  `binary_sensor.exterieur_slm_portier_personne`, `light.lumiere_de_lexterieur`
triggers:
  - trigger: state
    entity_id:
      - binary_sensor.exterieur_slm_portier_visiteur
    to:
      - "on"
  - trigger: state
    entity_id:
      - binary_sensor.exterieur_slm_portier_personne
    to:
      - "on"
    enabled: true
conditions: []
actions:
  - if:
      - condition: sun
        before: sunrise
        before_offset: "1800"
        after: sunset
        after_offset: "-1800"
    then:
      - action: light.turn_on
        target:
          entity_id:
            - light.lumiere_de_lexterieur
        data: {}
      - delay:
          hours: 0
          minutes: 0
          seconds: 5
          milliseconds: 0
  - if:
      - condition: light.is_on
        target:
          entity_id:
            - light.lumiere_de_lexterieur
        options:
          behavior: any
          for: "00:00:00"
    then:
      - delay:
          hours: 0
          minutes: 5
          seconds: 0
          milliseconds: 0
      - action: light.turn_off
        target:
          entity_id:
            - light.lumiere_de_lexterieur
        data: {}
mode: restart
