alias: Notification de défaut du réfrigérateur
description: >-
  **Statut :** Finalisé

  **Evolution :** Aucune


  **Déclencheurs :**

  - Changement de la température du frigo ou du congélateur

  - Déconnexion réseau de l'interface du réfrigérateur (device tracker passe de
  "home")


  **Conditions :**

  - Les capteurs de température et le device_tracker ne doivent pas être à
  unknown/unavailable


  **Fonctionnement :**

  1. Si la température du frigo est hors plage [2-4°C], OU le congélateur hors
  plage [-20 à -18°C], OU l'interface réseau du frigo n'est plus détectée →
  envoie un SMS d'alerte.


  **Entités principales :**

  - `sensor.refrigerateur_temperature_du_frigo` /
  `sensor.refrigerateur_temperature_du_congelateur` : températures

  - `device_tracker.samsung_refrigerator` : supervision réseau du frigo
triggers:
  - trigger: state
    entity_id:
      - sensor.refrigerateur_temperature_du_frigo
      - sensor.refrigerateur_temperature_du_congelateur
    to: null
    id: Température
  - trigger: state
    entity_id:
      - device_tracker.samsung_refrigerator
    to:
      - not_home
      - home
    for:
      hours: 0
      minutes: 0
      seconds: 0
    id: Présence
conditions:
  - condition: not
    conditions:
      - condition: state
        entity_id: sensor.refrigerateur_temperature_du_frigo
        state:
          - unknown
          - unavailable
  - condition: not
    conditions:
      - condition: state
        entity_id: sensor.refrigerateur_temperature_du_congelateur
        state:
          - unknown
          - unavailable
  - condition: not
    conditions:
      - condition: state
        entity_id: device_tracker.samsung_refrigerator
        state:
          - unknown
          - unavailable
actions:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - Température
        sequence:
          - if:
              - condition: or
                conditions:
                  - condition: not
                    conditions:
                      - condition: numeric_state
                        entity_id: sensor.refrigerateur_temperature_du_frigo
                        above: 2
                        below: 4
                  - condition: not
                    conditions:
                      - condition: numeric_state
                        entity_id: sensor.refrigerateur_temperature_du_congelateur
                        above: -20
                        below: -18
            then:
              - action: script.turn_on
                target:
                  entity_id:
                    - script.notification_sms
                data:
                  variables:
                    message_type: Alerte
                    message_sms: Problème de température dans le réfrigérateur
      - conditions:
          - condition: trigger
            id:
              - Présence
        sequence:
          - if:
              - condition: not
                conditions:
                  - condition: state
                    entity_id: device_tracker.samsung_refrigerator
                    state:
                      - home
            then:
              - action: script.turn_on
                target:
                  entity_id:
                    - script.notification_sms
                data:
                  variables:
                    message_type: Alerte
                    message_sms: Problème de connexion/alimentation du réfrigérateur
mode: single
