alias: Notification appareils en batterie faible - Mail hebdomadaire
description: >-
  **Statut :** Finalisé

  **Evolution :** Aucune


  **Déclencheurs :**

  - Déclenchement hebdomadaire (selon configuration)


  **Fonctionnement :**

  1. Envoie un mail récapitulatif des appareils dont la batterie est en dessous
  du seuil d'alerte.
triggers:
  - at: "19:00:00"
    weekday:
      - fri
    trigger: time
conditions: []
actions:
  - variables:
      low_battery_devices: |
        {% set devices = namespace(list=[]) %}
        {% for entity_id in integration_entities('battery_notes') %}
          {% set state = states[entity_id] %}
          {% if state and state.domain == 'sensor' and state.attributes.get('battery_low', false) %}
            {% set devices.list = devices.list + [{
              'name': state.attributes.get('device_name', entity_id),
              'battery_type_and_quantity': state.attributes.get('battery_type_and_quantity', 'Inconnu'),
              'battery_level': state.state
            }] %}
          {% endif %}
        {% endfor %}
        {{ devices.list }}
  - condition: template
    value_template: "{{ low_battery_devices | length > 0 }}"
  - variables:
      message_mail: |
        Liste des appareils avec batterie faible :
        {% for device in low_battery_devices -%}
          - {{ device.name }} à {{ device.battery_level | int }}% : {{ device.battery_type_and_quantity }}
        {% endfor %}
  - action: script.notification_mail
    data:
      message_type: Batteries
      message_mail: "{{ message_mail }}"
mode: restart
