id: '1777724559400'
alias: 🔓 Ouverture porte — P100 unique
description: ''
triggers:
- trigger: state
  entity_id:
  - binary_sensor.p100_boite_aux_lettres_contact
  to:
  - 'on'
conditions:
- condition: template
  value_template: '{{ (now() - states.binary_sensor.p100_boite_aux_lettres_contact.last_changed).total_seconds()
    < 1 }}

    '
actions:
- delay:
    seconds: 5
- condition: template
  value_template: '{{ (now() - states.binary_sensor.p100_boite_aux_lettres_contact.last_changed).total_seconds()
    < 5 }}

    '
- choose:
  - conditions:
    - condition: state
      entity_id: input_boolean.courrier_en_attente
      state: 'on'
    sequence:
    - action: input_boolean.turn_off
      target:
        entity_id: input_boolean.courrier_en_attente
    - variables:
        message_courrier: La boîte aux lettres a été vidée
  - conditions:
    - condition: state
      entity_id: input_boolean.courrier_en_attente
      state: 'off'
    sequence:
    - variables:
        message_courrier: Un colis vient d'être déposé
- if:
  - condition: template
    value_template: '{{ message_courrier != null }}'
  then:
  - action: script.notification_vocale
    data:
      message_vocal: '{{ message_courrier }}'
  - action: script.notification_sms
    data:
      message_type: Boite aux lettres
      message_sms: '{{ message_courrier }}'
mode: single
