id: '1777921394418'
alias: Surveillance - Automatisations inactives
description: ''
triggers:
- at: 09:00:00
  trigger: time
actions:
- variables:
    message: "{% set seuil = now() - timedelta(days=7) %} {% set inactives = states.automation\
      \ \n   | selectattr('attributes.last_triggered', 'ne', None)\n   | selectattr('attributes.last_triggered',\
      \ 'lt', seuil) \n   | list %}\n{% if inactives %} Pas déclenchées depuis 7 jours\
      \ : {% for a in inactives %} - {{ a.name }} (last: {{ a.attributes.last_triggered\
      \ | as_timestamp | timestamp_custom('%d/%m %H:%M') }}) {% endfor %} {% else\
      \ %} Toutes les automatisations ont tourné récemment. {% endif %}\n"
- if:
  - condition: template
    value_template: '{{ message != null }}'
  then:
  - action: script.notification_sms
    data:
      message_type: Automatisations inactives
      message_sms: '{{ message }}'
